config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  get 'page/index'

  authenticated :user do
    resources :notes
    root to: "notes#index", as: :notes_root
  end
  
  root to: "page#index"
  
  get "about", to: "page#about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :notes
  
  belongs_to :user
  
  validates :name, presence: true
  
  # Doesn't seem to work as it should (case-insensitve validation)
  # Else the custom validation category_unique_to_user isn't required
  #
  # validates :name, uniqueness: {
  #   scope: :user_id,
  #   message: 'category name must be unique to user',
  #   case_sensitive: true
  # }
  
  validate :category_unique_to_user
  
  def category_unique_to_user
    unless name_doesnt_exist_for_user?
      errors.add(:name, "That category already exists.")
    end
  end
  
  protected
  
  def name_doesnt_exist_for_user?
    # the code below is shorter but fails the test because
    # of the use of associations
    # self.user.categories.where('lower(name) = lower(?)', self.name).empty?
    duplicates = self.class.where('lower(name) = lower(?)', self.name)
    unless duplicates.empty?
      duplicates.each do |duplicate|
        return false if duplicate.user == self.user
      end
    end
    
    return true
  end
  
end

app/models/filter.rb
class Filter
  attr_accessor :category_id
  
  def initialize(category_id = "")
    self.category_id = category_id      
  end
end

app/models/note.rb
class Note < ApplicationRecord
  attr_accessor :new_category  # for creating categories
  
  belongs_to :user
  belongs_to :category
  
  validates :title, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :notes
  has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :find_note, only: [:show, :edit, :update, :destroy]
  before_action :check_owner, only: [:show, :edit, :update, :destroy]

  def index
    @notes_empty = current_user.notes.empty?
    if @notes_empty
      render :index and return  
    end
    
    @notes = nil
    category_id = ""
    if filter_by_category?
      category_id = params[:filter][:category_id]
      unless category_id.blank?
        @q = current_user.notes.ransack(category_id_eq: category_id) 
        @notes = @q.result
      end
    end
     
    if @notes.nil?
      @q = current_user.notes.ransack(params[:q])
      @notes = @q.result
    end
    
    @filter_shown = current_user.categories.any?
    @filter = Filter.new(category_id)
  end
  
  def show
  end
  
  def new
    @note = Note.new
  end
  
  def create
    if add_category?
     add_category_and_render('new')
    else
      @note = current_user.notes.build(note_params)
      if @note.save
        redirect_to @note
      else
        render 'new'
      end
    end
  end
  
  def edit
  end
  
  def update
    if add_category?
      add_category_and_render('edit')
    else
      if @note.update(note_params)
        redirect_to @note
      else
        render 'edit'
      end
    end
  end
  
  def destroy
    @note.destroy
    redirect_to notes_path
  end
  
  private
  
  def find_note
    @note = Note.find(params[:id])
  end
  
  def note_params
    params.require(:note).permit(:title, :content, :category_id, :new_category)
  end
  
  def add_category?
    params[:commit] == "Add Category"  
  end
  
  def filter_by_category?
    params[:commit] == "Filter by Category" 
  end
  
  def check_owner
    note = Note.find(params[:id])
    if current_user != note.user
      redirect_to notes_path 
    end
  end
  
  def add_category_and_render(template)
    @note = Note.new(note_params)
    @category = Category.new(name: note_params[:new_category], user: current_user)
    if @category.save
      @note.category = @category
      render template
    else
      @note.errors.add(:new_category, "can't be blank.")
      render template
    end  
  end
  
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sign_up_text
    raw('<span class="glyphicon glyphicon-user"></span> Sign Up')
  end
  
  def login_text
    raw('<span class="glyphicon glyphicon-log-in"></span> Login')
  end
  
  def new_note_text
    raw('<span class="glyphicon glyphicon-list-alt"></span> New Note')
  end
  
  def logout_text
    raw('<span class="glyphicon glyphicon-log-out"></span> Logout')
  end
  
  def edit_profile_text  
    raw('<span class="glyphicon glyphicon-user"></span> Edit Profile')  
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sense Notes - <%= @page_title || "Notes" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller_name == 'page' ? 'main' : '' %>">
    
    <nav class="navbar navbar-inverse navbar-fixed-top role="navigation">
     <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" 
           data-toggle="collapse" 
           data-target=".navbar-collapse">
          <span class="sr-only">Toggle Navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Sense Notes", root_path, class: "navbar-brand" %>
      </div>
      
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="<%= 'active' if current_page?(root_path) %>">
            <%= link_to "Home", root_path %>
          </li>
          <li class="<%= 'active' if current_page?(about_path) %>">
            <%= link_to "About", about_path %>
          </li>
        </ul>
        
       <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to new_note_text, new_note_path %>
          </li>
          <li>
            <%= link_to edit_profile_text, edit_user_registration_path %>
          </li>
          <li>
            <%= link_to logout_text, destroy_user_session_path,
                  method: :delete %>
          </li>
        <% else %>
          <li>
            <%= link_to sign_up_text, new_user_registration_path %>
          </li>
          <li>
            <%= link_to login_text, new_user_session_path %>
          </li>    
        <% end %>
      </ul>
        
      </div>
      

        
     </div><!-- Container -->
    </nav>  <!-- Navbar -->

    <% if controller_name == "notes_controller" %>
      <%= render 'layouts/flash_messages' %>
    <% end %>
    
    <%= yield %>
    
    </div> <!-- Container -->
  </body>
</html>

app/views/notes/_form.html.erb
  <%= form_for(@note, html: { class: "form-horizontal" }) do |f| %>
    <div>
      <% if @note.errors.any? %>
        <h4 class="text-danger"><%= pluralize(@note.errors.count, "error") %>
         prevented this 
         <% if @note.errors[:new_category].blank? %>
           note from being saved.
         <% else %>
           category from being added.
         <% end %>
        </h4>
        <ul>
          <% @note.errors.full_messages.each do |msg| %>
            <li><span class="text-danger"><%= msg %></span></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  
    <div class="form-group">
      <%= f.label :title, class: "control-label col-sm-1",
            for: "note_title" %>
      <div class="col-sm-6">
        <%= f.text_field :title, class: "form-control" %>
      </div>
    </div>
    
    <div class="form-group">
      <%= f.label :content, class: "control-label col-sm-1",
            for: "note_content" %>
      <div class="col-sm-6">
        <%= f.text_area :content, class: "form-control content-edit",
              rows: "12" %>
      </div>
    </div>
    
    <div class="form-group">
      <%= f.label :category_id, class: "control-label col-sm-1",
            for: "note_category_id" %>
      <div class="col-sm-3">
        <%= f.collection_select :category_id, Category.where(user: current_user),
            :id, :name, { include_blank: "Uncategorized", selected: @note.category_id },
            { class: "form-control" } %> 
      </div>
    </div>
    
    <div class="form-group">
      <div class="col-sm-3 col-sm-offset-1">
        <%= f.text_field :new_category, class: "form-control" %>
      </div>
      <div class="col-sm-3">
        <%= f.submit "Add Category", class: "btn btn-primary",
            data: { disable_with: "Adding Category..." } %>
      </div>
    </div>
    
    <div class="form-group">
      <div class="col-sm-offset-1 col-sm-6">
        <% if @note.new_record? %>
          <%= f.submit "Create", class: "btn btn-success btn-lg btn-space",
              data: { disable_with: "Creating..." } %>
          <%= link_to "Cancel", notes_path, class: "btn btn-default btn-lg" %>
        <% else %>
          <%= f.submit "Update", class: "btn btn-success btn-lg btn-space",
              data: { disable_with: "Updating... " } %>
          <%= link_to "Cancel", @note, class: "btn btn-default btn-lg" %>
        <% end %>
      </div>
    </div>
  <% end %>

app/views/notes/edit.html.erb
<%= @page_title = "Edit #{@note.title}" %>

<div class="container notes-main-note">
  <h1>Edit Note</h1>
  
  <%= render 'form' %>
</div>

app/views/notes/index.html.erb
<%= @page_title = "Notes" %>

<div class="container notes-main">
  <% unless @notes_empty %>
    <div class="search-forms">
      <%= search_form_for(@q, class: "form-inline") do |f| %>
        <div class="form-group">
          <%= f.search_field :title_or_content_cont, class: "form-control" %>
        </div>
        
        <%= f.submit "Search", class: "btn btn-success",
            data: { disable_with: "Searching..." } %>
      <% end %>
    </div>
    
    <% if @filter_shown %>
      <div class="category-filter">
        <%= form_tag(notes_path, method: :get, class: "form-inline") do %>
              <%= collection_select :filter, :category_id, Category.where(user: current_user),
                :id, :name, { include_blank: "All Categories" },
                { class: "form-control" } %> 
          
          <%= submit_tag "Filter by Category", class: "btn btn-success",
              data: { disable_with: "Filtering..." } %>
        <% end %>
      </div>
    <% end %>
    
    <% if @notes.any? %>
      <table class="table table-hover table-bordered">
        <thead>
          <tr>
            <th><%= sort_link(@q, :title) %></th>
            <th><%= sort_link(@q, :content) %></th>    
            <th><%= sort_link(@q, :category_name) %></th> 
          </tr>
        </thead>    
        <tbody>
          <% @notes.each do |note| %>
            <tr>
              <td><%= link_to note.title, note %></td>      
              <td><%= truncate(strip_tags(note.content),
                      length: 100) %>
              </td>
              <% if note.category.nil? %>
                <td><span class="label label-primary">Uncategorized</span></td>
              <% else %>
                <td><span class="label label-primary"><%= note.category.name %></span></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <h3>There are no notes that matches your search term.</h3>
      <p><%= link_to "Return", notes_path, class: "btn btn-primary" %></p>
    <% end %>
    
  <% else %>
    <h3>You haven't made any notes yet.
        Want to create one?</h3>
    <br>
    
    <%= link_to "Create New Note", new_note_path, class: "btn btn-success" %>
  <% end %>
  
</div> <!-- Container -->

app/views/notes/new.html.erb
<%= @page_title = "New Note" %>

<div class="container notes-main-note">
  <h1>Create New Note</h1>
  
  <%= render 'form' %>
</div>

app/views/notes/show.html.erb
<%= @page_title = @note.title %>

<div class="container notes-main">
  <div class="row">
    
    <div class="col-sm-7">
      <div class="panel panel-success">
        <div class="panel-heading">
          <div class="panel-title"><strong><%= @note.title %></strong></div>
        </div>
        <div class="panel-body">
          <p><%= @note.content.html_safe %></p>
        </div>
        <div class="panel-footer">
        <% if @note.category_id.nil? %>
          <p class="label label-primary">Uncategorized</p>
        <% else %>
          <p class="label label-primary"><%= @note.category.name %></p>
        <% end %>
      </div>
    </div>
  
    <div class="btn-actions">
      <%= link_to "Edit Note", edit_note_path(@note),
          class: "btn btn-success btn-space" %>
      <%= link_to "Delete Note", note_path(@note), method: :delete,
          data: { confirm: "Are you sure you want to delete this note?",
                  commit: "Yes", cancel: "No" },
          class: "btn btn-primary " %>
    </div>
  
    </div>
  </div>
</div>

app/views/page/about.html.erb
<%= @page_title = "About" %>

<div class="container pad-top site-text">
  <h1>About</h1>
  <p class="lead">This app is a personal project of Michael Palad.</p>
  <p><a href="https://github.com/michael-palad" target="_blank">
      Michael's Github</a>
  </p>
  <p><a href="https://github.com/michael-palad/sense-notes" target="_blank">
      This app's Github page</a>
  </p>
</div>

app/views/page/index.html.erb
<%= @page_title = "Home" %>

<div class="jumbotron main">
  <div class="container main site-text">
      <h1>Sense Notes</h1>
      <p class="lead">Take notes so that you can recall things
      in your personal life.</p>
      <%= link_to raw("Sign Up &raquo;"), new_user_registration_path,
            class: "btn btn-primary btn-lg", type: "button" %>
  </div>
</div>